
resource "docker_image" "graylog" {
  name = "graylog/graylog:4.2"
  keep_locally = true
} 
#Password is generated by:
#echo -n "Admin123@123" && head -1 </dev/stdin | tr -d '\n' | sha256sum | cut -d" " -f1
#output: 6e9b1d03e641640ff2aaf3a4a77dff148297866a13e0bf8d854cc96c56baa8f0

resource "docker_container" "graylog" {
  count = 1
  name  = "graylog"
  links = [ "mongo", "elasticsearch" ]
  image = "${docker_image.graylog.name}"
  env = [
      "GRAYLOG_ROOT_USERNAME=graylog", 
      "GRAYLOG_ROOT_PASSWORD_SHA2=6e9b1d03e641640ff2aaf3a4a77dff148297866a13e0bf8d854cc96c56baa8f0", 
      "GRAYLOG_PASSWORD_SECRET=6e9b1d03e641640ff2aaf3a4a77dff148297866a13e0bf8d854cc96c56baa8f0",
      "GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/"
  ]
  ports {
    internal = 9000
    external = 9000
  }
  ports {
    internal = 5555
    external = 5555
  }
  
  ports{
    protocol = "udp"
    internal = 12202
    external = 12202
  }   
}